### PR TITLE
Make the backup cronjob use a non-root user

### PR DESCRIPTION
**Pull request by Hoid**
Currently, this cronjob runs as the root user. We want to change that so it is forced to use a non-root user. When deploying this cronjob, one can set the `runAsUser:` property in the `securityContext` block of the values.yaml file with the userid of the user you want to use.

### CODE REVIEW

**Review by pj-linebaugh — CHANGES_REQUESTED** [review]
Can you increase the minor versions for the helx and backup-pvc-cronjob charts and also use helm-docs to update the readmes?

**Comment by Hoid** [comment]
> Can you increase the minor versions for the helx and backup-pvc-cronjob charts and also use helm-docs to update the readmes?

Done

**Comment by Hoid** [comment]
Not sure why it's not showing the most recent commit, but I fixed the versions in the labels at the top of the README as well

**Comment by waTeim** [comment]
When testing, does this come into play at all?

    podSecurityContext: {}
    # fsGroup: 2000
    # runAsUser: 8888

 Is it important who the files are written/owned by since it's not root?

**Comment by pj-linebaugh** [comment]
> When testing, does this come into play at all?
> 
> ```
> podSecurityContext: {}
> # fsGroup: 2000
> # runAsUser: 8888
> ```
> 
> Is it important who the files are written/owned by since it's not root?

yes.  files/directories that to be backed up will need to be readable by whatever user the backup pod runs as.  Look at "Best Practices #3" in this [post](https://developers.redhat.com/articles/2021/11/11/best-practices-building-images-pass-red-hat-container-certification#best_practice__2__make_the_image_run_as_a_non_root_user).  I think this is the way we should be headed when we create images.

**Comment by Hoid** [comment]
@pj-linebaugh I updated the chart version and application version for the backup-pvc-cronjob, but just the chart version for the overall helx-chart, since it uses the new backup-pvc-cronjob version as a part of the chart, but I didn't change anything in the base helx-chart. Is this fine, or should I increment the application version of helx-chart too?

**Comment by pj-linebaugh** [comment]
This is a bit of a weird case for the backup-pvc-cronjob helm chart when it comes to the appVersion since we don't really make any changes in image, just the chart.  Since the main functionality is in the script that is in the chart I think it is appropriate to update the appVersion (in both places).

**Comment by Hoid** [comment]
Gotcha, okay. Done :)

**Pull request merged**
