### PR TITLE
kubernetes-image-puller

### PR DESCRIPTION
**Pull request by pj-linebaugh**
Modifications to use the newer kubernetes-image-puller to cache images on k8s nodes.

### CODE REVIEW

**Comment by pj-linebaugh** [comment]
@waTeim ?  This slip by?  Maybe I can get this in before Yaphet's PR?  ;)

**Comment by waTeim** [comment]
Let's make sure to reconcile all of this.  It's not clear from file_changed,  Is Chart.lock in or out?

**Comment by pj-linebaugh** [comment]
I removed it.  If we do end up wanting to keep track of it I suggest we add/modify it when the helm package files are created.

**Comment by waTeim** [comment]
Seems like it's one of those things that gets generated, never gets typed and whenever it doesn't, it's always an error.  So keep it out.

**Review by waTeim — APPROVED** [review]

**Pull request merged**
