### PR TITLE
Basic auth

### PR DESCRIPTION
**Pull request by YaphetKG**
Adds Ingress basic auth for main ingress. This is to allow some gatekeeping for newer search deployments. Users who don't have access to renci vpn would like to give deployments a green light before we make it public.

### CODE REVIEW

**Comment by YaphetKG** [comment]
https://renci.atlassian.net/browse/DUG-117?focusedCommentId=10417&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-10417

**Comment by waTeim** [comment]
Adding this feature should increase minor version

**Comment by waTeim** [comment]
This might take a long time, so I'm not going to insist on it since we primarily want to just get it done, but maybe the default password should be a randomly generated password  -- that you later have to check via getsecret -o yaml, etc.  That should be the subject of some follow on work though I suggest.

**Comment by YaphetKG** [comment]
I had thought of doing that , but the password needs to be accessible to htpasswd function on the helm side. I don't think there is a way to get the value from a secret and use it as a parameter for htpasswd function in helm while the same helm chart is also responsible to create the source secret .

**Comment by YaphetKG** [comment]
if we use random generator as a paramter for htpasswd , since that is a one way hash function we wouldn't be able to see what random password was used

**Review by waTeim — APPROVED** [review]

**Pull request merged**
